# App: AWS Customer CRUD
# Package: e2e
# File: test_requests.http
# Version: 0.0.6
# Author: Bobwares
# Date: Sat Jun 07 01:41:18 UTC 2025
# Description: Example HTTP request for hello world endpoint.
#
### Hello World
GET https://example.com/
